bookmark/urls.py
from django.contrib import admin
from django.urls import path

# 2차 URL

# name 의 목적 template  'list/' 의 목적 뷰를 연결하기 위해
from  .views import *
# app_name => 네임스페이스 // url 이름을 가지고 패턴을 찾고자 할 때 namespace를 사용하려면 app_name이 필수!
app_name = 'bookmark'
urlpatterns = [

    # 함수형뷰 : 함수형 이름만
    # 클래스형 뷰 : 클래스이름.as_view()

    path('', BookmarkListView.as_view(), name='list'),
    path('write/', BookmarkCreateView.as_view(), name='write'),
    path('update/<int:pk>', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BookmarkDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', BookmarkDetailView.as_view(), name='detail'),
    # re_path(regexp,,),
    # url(regexp, ?, ?)
]

mycite/urls.py
from django.contrib import admin
from django.urls import path, include

# 1차 URL
urlpatterns = [
    path('admin/', admin.site.urls),
    # 1차에서 2차인 bookmark url로 토스
    path('', include('bookmark.urls')),
]

bookmark/models.py
from django.db import models

# Create your models here.

# 데이터베이스 직접 접근하는 것이 아니라 ORM 기능을 통해서 접근
# 모델은 class로 만들다

class Bookmark(models.Model):
    # 필드 : 데이터베이스에 어떤 컬럼, 어떤 형태, 어떤 제약조건
    # 필드목적 : 프로트에서 어떤 form tag와 어떤 제약조건을 설정
    site_name = models.CharField(max_length=100)
    url = models.URLField('Site URL')

    # print 함수를 사용해서 객체를 출력할 때 출력될 내용을 반환하는 함수
    # 장고가 이걸 응용해서 화면에 객체를 html로 출력할 떄 내용을 활용하는 함수
    def __str__(self):
        return self.site_name + " : " + self.url

    class Meta:
        # 해당 모델에 대한 옵션 값
        # 정렬, 출력될 모델 이름
        ordering = ['-site_name']

    # Todo : get_absolute_url 리턴 페이지를 지정하지 않았을 경우 get_absolute_url로 이동한다.
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('bookmark:detail', args=[str(self.id)])

bookmark/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


# view 두 종류 : 함수형, 클래스형
# 클래스형 : 자주 쓰는 기능을 상속받아서 간단하게 생성

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Bookmark
from django.urls import reverse_lazy

# List View
class BookmarkListView(ListView):
    model = Bookmark
    # 클래스형 뷰는 기본적으로 렌더링할 템플릿 파일이 지정 되어있습니다.
    # bookmark/bookmark_list.html

class BookmarkCreateView(CreateView):
    model = Bookmark # 입력화면에 출력된 form tag를 자동으로 만들어줌
    # _form : create, update
    # default : form
    template_name_suffix = '_create'
    # 입력받을 필드 목록
    fields = ['site_name','url']
    # get_absolute_url
    success_url = reverse_lazy('list')

class BookmarkUpdateView(UpdateView):

    model = Bookmark
    fields = ['site_name', 'url']
    template_name_suffix = '_update'

class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')

class BookmarkDetailView(DetailView):
    model = Bookmark

# def list(request):
#     return HttpResponse("List Page")
#
# def write(request):
#     return HttpResponse("write Django")
#
# def update(request):
#     return HttpResponse("update Django")
#
# def delete(request):
#     return HttpResponse("delete Django")

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% block title %} Delete {% endblock %}
{% block content %}

<form action ="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger"> 진짜 삭제할래??? "{{object}}"?</div>
        <input type="submit" value="Delete" class="btn btn-danger">
</form>

{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}
{% block title %}Add New{% endblock %}
{% block content %}
    <form action="" method="post">

        <!--#csrf 공격-->
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Write" />
    </form>

???
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% block title %}Add New{% endblock %}
{% block content %}

        <!--#csrf 공격-->
        {% csrf_token %}
        {{ form.as_p }}
        {{object.site_name}}
        {{object.url}}

{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% block title %}Bookmarks{% endblock %}
{% block content %}
<div class="btn-group d-block text-right mb-1" role="group">
    <!--bookmark는 네임스페이스-->
  <a href="{% url 'bookmark:write' %}" class="btn btn-info">Add</a>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Site</th>
      <th scope="col">URL</th>
      <th scope="col">Modify</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for bookmark in object_list %}
        <tr>
            <td>
                {{ forloop.counter }}
            </td>
            <td>

                <a href="{% url 'bookmark:detail' bookmark.id %}" class="btn btn-success btn-sm">{{bookmark.site_name}}</a>
            </td>
            <td>
                <a href="{{bookmark.url}}" target="_blank">{{bookmark.url}}</a>
            </td>
            <td>
                <a href="{% url 'bookmark:update' bookmark.id %}" class="btn btn-success btn-sm">modify</a>
            </td>
            <td>
                <a href="{% url 'bookmark:delete' bookmark.id %}" class="btn btn-danger btn-sm">delete</a>
            </td>
        </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}
{% block title %}Add New{% endblock %}
{% block content %}
    <form action="" method="post">

        <!--#csrf 공격-->
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="Update" />
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <header class="py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">

          </div>
          <div class="col-4 text-center">
            <a class="header-logo text-dark" href="/">Bookmark</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
          </div>
        </div>
      </header>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>